apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-frontend
  namespace: ns-stocksanalyzer
  labels:
    component: frontend
    version: 0.1.0
    app: stocksanalyzer
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
      version: 0.1.0
      app: stocksanalyzer
      env: prod
  template:
    metadata:
      labels:
        component: frontend
        version: 0.1.0
        app: stocksanalyzer
        env: prod
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

